version: '3.8'

services:
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: backend
            MONGO_INITDB_ROOT_PASSWORD: backend1!
    sa_mongo:
        image: mongo-express
        container_name: sa_mongo
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: backend
            ME_CONFIG_MONGODB_ADMINPASSWORD: backend1!
            ME_CONFIG_MONGODB_URL: mongodb://backend:backend1!@mongo:27017/
            ME_CONFIG_BASICAUTH: 0

    sa_redis:
        image: redis
        container_name: sa_redis
        environment:
            - REDIS_PASSWORD=backend!
        ports:
            - "6379:6379"

    sa_bot:
        container_name: sa_bot
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
            network: host
        volumes:
            - .:/app